new upstream 4.17.2
ansible/cloudstack-test-container pull request #15
Opened 2023-01-21 08:25 UTC by resmo

/cc @mattclay @rvalle 

supersedes / closes #13

2023-01-21 09:31 UTC, resmo commented
FATAL: The 7 integration test(s) listed below (out of 51) failed. See error output above for details:
cs_cluster
cs_host
cs_instance
cs_pod
cs_service_offering
cs_zone

2023-01-21 10:06 UTC, resmo commented
adjustments to api changes for 4.17 https://github.com/ngine-io/ansible-collection-cloudstack/pull/118

2023-01-21 15:23 UTC, resmo commented
@mattclay ready to merge

2023-01-23 17:05 UTC, mattclay requested changes
@resmo Thanks for updating this. I've requested one minor change.

2023-01-23 17:05 UTC, mattclay commented on Dockerfile
> +FROM ubuntu:22.04
To avoid Docker Hub rate limiting, we should use the images mirrored at `quay.io/bedrock`:

```suggestion
FROM quay.io/bedrock/ubuntu:22.04
```

2023-01-23 17:09 UTC, mattclay commented on Dockerfile
> +FROM ubuntu:22.04
FYI - The bedrock mirror is managed by https://github.com/ansible/bedrock

2023-01-23 17:10 UTC, mattclay approved these changes

2023-01-23 17:17 UTC, resmo commented on Dockerfile
> +FROM ubuntu:22.04
ah nice.

2023-01-23 17:28 UTC, mattclay commented on Dockerfile
> +RUN apt-get -qq update && apt-get -qq dist-upgrade && apt-get install -qq -y --no-install-recommends \
I just noticed that this step is taking quite a long time. With the `-qq` it's impossible to see what's taking so long.

Can we drop the `-qq` and also omit the `dist-upgrade`?

```suggestion
RUN apt-get update && apt-get install -y --no-install-recommends \
```

2023-01-23 17:53 UTC, mattclay commented on Dockerfile
> +RUN apt-get -qq update && apt-get -qq dist-upgrade && apt-get install -qq -y --no-install-recommends \
Perhaps AZP was just slow to show the output. Looking at the run for the previous commit it seems this step was less than 3 minutes, and it did provide progress details. Other build steps were responsible for taking the bulk of the time.

2023-01-23 18:00 UTC, mattclay commented
/azp run

2023-01-23 18:04 UTC, mattclay commented
@resmo I pushed a commit to update the AZP configuration to use our new container build process. The new builds are multi-arch (x86_64 and aarch64).

2023-01-23 19:06 UTC, mattclay commented
@resmo The new build worked for x86_64 -- and seems to be much faster. It finished in about 30 minutes instead of 39. Unfortunately the aarch64 build seems to have issues with the `npm build` command. For some reason it seems to be using an old version of node-gyp (3.8.0) which requires Python 2.7:

https://dev.azure.com/ansible/cloudstack-test-container/_build/results?buildId=66484&view=logs&j=3fbf534b-6b38-5a58-46dd-b0a7c7caed3f&t=99fc23f6-cf29-5ed6-13c8-64c0e2150ed1&l=188075

2023-01-24 07:26 UTC, resmo commented
> @resmo I pushed a commit to update the AZP configuration to use our new container build process. The new builds are multi-arch (x86_64 and aarch64).

multi-arch would be nice however, I really don't have a usecase for aarch64 right now. I am fine if we skip this for the future.

2023-01-24 20:18 UTC, mattclay commented
@resmo It would be nice to have working multi-arch builds, as all of our other maintained containers do. However, that's something we can hopefully address later -- so I've removed the `aarch64` build from the matrix for now.

2023-01-24 21:06 UTC, mattclay commented
@resmo Is there anything else you'd like to change before I merge this and publish a new version of the container?

2023-01-25 07:42 UTC, resmo commented
:shipit:

2023-01-25 16:46 UTC, merged